### ISSUE TITLE
✅ Erro apresentado ao clicar no botão 'Entrar' sem preencher os campos

### ISSUE THREAD

**Issue by monicaasc** [ThallesAraujo/corretorPontoReact#1]
- Clicar no botão 'Entrar' sem preencher os campos de 'Usuário' e 'Senha'
- Validar que retorna 400 e não existe um tratamento na mensagem, o erro é apresentado para o usuário

O mesmo ocorre quando credenciais incorretas são inseridas. Melhorar o feedback

![image](https://user-images.githubusercontent.com/6333084/80415752-554a3a80-88a9-11ea-9446-1270d80b50de.png)

**Comment by ThallesAraujo** [comment]
Adicionadas tooltips nos campos
![image](https://user-images.githubusercontent.com/17062668/82594758-f65fa480-9b7a-11ea-9e32-d6d1b04df4be.png)

**Comment by monicaasc** [comment]
Validado :ok:
![image](https://user-images.githubusercontent.com/6333084/83082491-01727300-a05a-11ea-98f5-d92890dde9c5.png)
![image](https://user-images.githubusercontent.com/6333084/83082535-1949f700-a05a-11ea-9df7-7ca5fa7dc532.png)
