### ISSUE TITLE
✅ SUGESTÃO: Abreviar as palavras 'Entrada' e 'Saída' no PDF

### ISSUE THREAD

**Issue by monicaasc** [ThallesAraujo/corretorPontoReact#13]
- Gerar PDF
- Validar que se for utilizado as abreviações é possível reduzir o tamanho da coluna de 'Entrada 1'
- Alterar no PDF o 'Entrada 1' para 'Ent', e 'Saída 1' e 'Sai1', para facilitar a visualização

![image](https://user-images.githubusercontent.com/6333084/80429006-8898c380-88c1-11ea-97f0-db5678dd8e50.png)

**Comment by ThallesAraujo** [comment]
Implementada no commit e91cf3fd87afb7961d88ecc7fcb15d34349f1a5b

**Comment by monicaasc** [comment]
Validado :ok:

![image](https://user-images.githubusercontent.com/6333084/83083158-ca04c600-a05b-11ea-972c-83015e85aa6e.png)
