### ISSUE TITLE
BUG: Indica sábados como inconsistência

### ISSUE THREAD

**Issue by ThallesAraujo** [ThallesAraujo/corretorPontoReact#16]
Devido ao uso do moment, os sábados estão sendo indicados como inconsistência

**Comment by ThallesAraujo** [comment]
Corrigido -> Commit 1157a27538952ad6a5d11577176a256d7fe4c3ea

**Comment by ThallesAraujo** [comment]
Corrigido -> Commit 1157a27538952ad6a5d11577176a256d7fe4c3ea

**Comment by monicaasc** [comment]
Validado :ok:
