### ISSUE TITLE
FEATURE: Selecionar mês e ano para visualizar pontos

### ISSUE THREAD

**Issue by ThallesAraujo** [ThallesAraujo/corretorPontoReact#24]
Permitir que o mês e o ano da visualização de pontos possa ser selecionados

**Comment by monicaasc** [comment]
@ThallesAraujo , nessa feature poderia ser interessante limitar apenas a visualização nos meses anteriores ao atual, já que não faz sentido realizar edições, bem como não realizar requisição aos meses seguintes ao atual. Faz sentido pra ti? (=
