### ISSUE TITLE
BUG: Dropdown com os meses está com texto em branco (dando aparência de que a listagem está vazia)

### ISSUE THREAD

**Issue by wallaceab** [ThallesAraujo/corretorPontoReact#25]
Passos para reproduzir o problema:

- Fazer login na aplicação
- Logo na primeira tela abrir o dropdown com a lista de meses (estão todos em branco)
- Evidência: https://imgur.com/a/lK8WlKf 

Ambiente utilizado:
- Windows 10 (Modo escuro)
- Chrome versão 81.0.4044.138 (Versão oficial) 64 bits

**Comment by ThallesAraujo** [comment]
Problema de web components utilizado pelo Chrome. Ajustar dark mode

**Comment by wallaceab** [comment]
Problema solucionado! Show de bola!

**Comment by monicaasc** [comment]
Validado :ok:

![image](https://user-images.githubusercontent.com/6333084/83085474-6e8a0680-a062-11ea-915b-53749df5deb4.png)
