### ISSUE TITLE
✅ SUGESTÃO: Incluir informação de qual as credenciais devem ser utilizadas

### ISSUE THREAD

**Issue by monicaasc** [ThallesAraujo/corretorPontoReact#3]
- Acessar a tela de login
- Validar que não apresenta nenhuma informação de qual credencial deve ser utilizada
   - Seria interessante incluir uma indicação de qual usuário e senha deve ser utilizado

**Comment by ThallesAraujo** [comment]
Adicionado: tooltips de explicação dos campos, exibidas ao manter o mouse sobre os mesmos
![image](https://user-images.githubusercontent.com/17062668/82595019-4f2f3d00-9b7b-11ea-92f9-14ab3c2c9218.png)

**Comment by monicaasc** [comment]
Validado :ok:
