### ISSUE TITLE
✅ Alterar posição da data no PDF

### ISSUE THREAD

**Issue by monicaasc** [ThallesAraujo/corretorPontoReact#5]
- Alterar posição da Data para facilitar a visualização
   - Apresentar a Data - Dia, ex.: 16/04/2020 - Qui

![image](https://user-images.githubusercontent.com/6333084/80423569-a01e7f00-88b6-11ea-8444-3d760a7b4851.png)

**Comment by ThallesAraujo** [comment]
Implementada no commit e91cf3fd87afb7961d88ecc7fcb15d34349f1a5b

**Comment by monicaasc** [comment]
Validado :ok:

![image](https://user-images.githubusercontent.com/6333084/83082756-aee58680-a05a-11ea-8ed9-b29c9bddfae2.png)
